# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chart_tool.ui'
#
# Created: Tue May 15 09:01:57 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(540, 643)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_exit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(450, 560, 75, 23))
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 15, 151, 41))
        self.label.setMinimumSize(QtCore.QSize(0, 41))
        self.label.setMaximumSize(QtCore.QSize(16777215, 41))
        self.label.setSizeIncrement(QtCore.QSize(2, 2))
        self.label.setBaseSize(QtCore.QSize(0, 2))
        self.label.setAcceptDrops(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_selected = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_selected.setGeometry(QtCore.QRect(160, 25, 261, 23))
        self.lineEdit_selected.setObjectName(_fromUtf8("lineEdit_selected"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox)
        self.pushButton_browse.setGeometry(QtCore.QRect(430, 25, 75, 23))
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 251, 401))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.comboBox_bar = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_bar.setGeometry(QtCore.QRect(10, 20, 231, 22))
        self.comboBox_bar.setObjectName(_fromUtf8("comboBox_bar"))
        self.comboBox_bar.addItem(_fromUtf8(""))
        self.comboBox_bar.addItem(_fromUtf8(""))
        self.comboBox_bar.addItem(_fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 231, 261))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.checkBox_Btitle = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Btitle.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_Btitle.setChecked(True)
        self.checkBox_Btitle.setObjectName(_fromUtf8("checkBox_Btitle"))
        self.checkBox_Bylabel = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Bylabel.setGeometry(QtCore.QRect(10, 70, 81, 17))
        self.checkBox_Bylabel.setObjectName(_fromUtf8("checkBox_Bylabel"))
        self.checkBox_Bxlabel = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Bxlabel.setGeometry(QtCore.QRect(10, 45, 76, 17))
        self.checkBox_Bxlabel.setObjectName(_fromUtf8("checkBox_Bxlabel"))
        self.checkBox_Blegend = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Blegend.setGeometry(QtCore.QRect(10, 95, 70, 17))
        self.checkBox_Blegend.setChecked(True)
        self.checkBox_Blegend.setObjectName(_fromUtf8("checkBox_Blegend"))
        self.lineEdit_Btitle = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_Btitle.setGeometry(QtCore.QRect(90, 20, 131, 21))
        self.lineEdit_Btitle.setObjectName(_fromUtf8("lineEdit_Btitle"))
        self.lineEdit_Bxlabel = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_Bxlabel.setGeometry(QtCore.QRect(90, 45, 131, 21))
        self.lineEdit_Bxlabel.setObjectName(_fromUtf8("lineEdit_Bxlabel"))
        self.lineEdit_Bylabel = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_Bylabel.setGeometry(QtCore.QRect(90, 70, 131, 21))
        self.lineEdit_Bylabel.setObjectName(_fromUtf8("lineEdit_Bylabel"))
        self.lineEdit_Blegend = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_Blegend.setGeometry(QtCore.QRect(90, 95, 131, 21))
        self.lineEdit_Blegend.setObjectName(_fromUtf8("lineEdit_Blegend"))
        self.comboBox_Blegend = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_Blegend.setGeometry(QtCore.QRect(100, 120, 121, 22))
        self.comboBox_Blegend.setObjectName(_fromUtf8("comboBox_Blegend"))
        self.comboBox_Blegend.addItem(_fromUtf8(""))
        self.comboBox_Blegend.addItem(_fromUtf8(""))
        self.comboBox_Blegend.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.checkBox_Bpercentage = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Bpercentage.setGeometry(QtCore.QRect(10, 210, 81, 17))
        self.checkBox_Bpercentage.setChecked(True)
        self.checkBox_Bpercentage.setObjectName(_fromUtf8("checkBox_Bpercentage"))
        self.pushButton_Bprocess = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_Bprocess.setGeometry(QtCore.QRect(131, 230, 91, 23))
        self.pushButton_Bprocess.setObjectName(_fromUtf8("pushButton_Bprocess"))
        self.checkBox_Psorted = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_Psorted.setGeometry(QtCore.QRect(10, 235, 81, 17))
        self.checkBox_Psorted.setChecked(True)
        self.checkBox_Psorted.setObjectName(_fromUtf8("checkBox_Psorted"))
        self.comboBox_Bbcolor = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_Bbcolor.setGeometry(QtCore.QRect(100, 150, 121, 22))
        self.comboBox_Bbcolor.setObjectName(_fromUtf8("comboBox_Bbcolor"))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.comboBox_Bbcolor.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 91, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox_Bpcolor = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_Bpcolor.setGeometry(QtCore.QRect(100, 180, 121, 22))
        self.comboBox_Bpcolor.setObjectName(_fromUtf8("comboBox_Bpcolor"))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.comboBox_Bpcolor.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(10, 180, 91, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_Bcolumn1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_Bcolumn1.setGeometry(QtCore.QRect(10, 65, 111, 20))
        self.lineEdit_Bcolumn1.setObjectName(_fromUtf8("lineEdit_Bcolumn1"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(130, 50, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_Bcolumn2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_Bcolumn2.setGeometry(QtCore.QRect(130, 65, 111, 20))
        self.lineEdit_Bcolumn2.setObjectName(_fromUtf8("lineEdit_Bcolumn2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(130, 90, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_Bfield = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_Bfield.setGeometry(QtCore.QRect(130, 105, 111, 20))
        self.lineEdit_Bfield.setText(_fromUtf8(""))
        self.lineEdit_Bfield.setObjectName(_fromUtf8("lineEdit_Bfield"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spinBox_Bangle = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_Bangle.setGeometry(QtCore.QRect(10, 105, 51, 20))
        self.spinBox_Bangle.setToolTip(_fromUtf8(""))
        self.spinBox_Bangle.setSpecialValueText(_fromUtf8(""))
        self.spinBox_Bangle.setProperty("value", 90)
        self.spinBox_Bangle.setObjectName(_fromUtf8("spinBox_Bangle"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 90, 251, 401))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_pie = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_pie.setGeometry(QtCore.QRect(10, 20, 231, 22))
        self.comboBox_pie.setObjectName(_fromUtf8("comboBox_pie"))
        self.comboBox_pie.addItem(_fromUtf8(""))
        self.comboBox_pie.addItem(_fromUtf8(""))
        self.comboBox_pie.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(130, 50, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 130, 231, 261))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_Ptitle = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_Ptitle.setGeometry(QtCore.QRect(90, 20, 131, 21))
        self.lineEdit_Ptitle.setObjectName(_fromUtf8("lineEdit_Ptitle"))
        self.checkBox_Ptitle = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_Ptitle.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_Ptitle.setChecked(True)
        self.checkBox_Ptitle.setObjectName(_fromUtf8("checkBox_Ptitle"))
        self.checkBox_Pexploded = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_Pexploded.setGeometry(QtCore.QRect(10, 100, 81, 17))
        self.checkBox_Pexploded.setObjectName(_fromUtf8("checkBox_Pexploded"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 45, 91, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_Plegend = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_Plegend.setGeometry(QtCore.QRect(100, 45, 121, 22))
        self.comboBox_Plegend.setObjectName(_fromUtf8("comboBox_Plegend"))
        self.comboBox_Plegend.addItem(_fromUtf8(""))
        self.comboBox_Plegend.addItem(_fromUtf8(""))
        self.pushButton_Pprocess = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_Pprocess.setGeometry(QtCore.QRect(131, 230, 91, 23))
        self.pushButton_Pprocess.setObjectName(_fromUtf8("pushButton_Pprocess"))
        self.spinBox_Pcollapsed = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_Pcollapsed.setGeometry(QtCore.QRect(110, 120, 51, 20))
        self.spinBox_Pcollapsed.setToolTip(_fromUtf8(""))
        self.spinBox_Pcollapsed.setSpecialValueText(_fromUtf8(""))
        self.spinBox_Pcollapsed.setProperty("value", 4)
        self.spinBox_Pcollapsed.setObjectName(_fromUtf8("spinBox_Pcollapsed"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 125, 131, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_Pcolor = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_Pcolor.setGeometry(QtCore.QRect(100, 75, 121, 22))
        self.comboBox_Pcolor.setObjectName(_fromUtf8("comboBox_Pcolor"))
        self.comboBox_Pcolor.addItem(_fromUtf8(""))
        self.comboBox_Pcolor.addItem(_fromUtf8(""))
        self.comboBox_Pcolor.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(10, 75, 91, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_Pcolumn1 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_Pcolumn1.setGeometry(QtCore.QRect(10, 65, 111, 20))
        self.lineEdit_Pcolumn1.setObjectName(_fromUtf8("lineEdit_Pcolumn1"))
        self.lineEdit_Pcolumn2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_Pcolumn2.setGeometry(QtCore.QRect(130, 65, 111, 20))
        self.lineEdit_Pcolumn2.setObjectName(_fromUtf8("lineEdit_Pcolumn2"))
        self.lineEdit_Pfield = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_Pfield.setGeometry(QtCore.QRect(130, 105, 111, 20))
        self.lineEdit_Pfield.setText(_fromUtf8(""))
        self.lineEdit_Pfield.setObjectName(_fromUtf8("lineEdit_Pfield"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(130, 90, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 500, 521, 41))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 590, 541, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(17, 560, 431, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit", None))
        self.groupBox.setTitle(_translate("MainWindow", "Choose Excel File", None))
        self.label.setText(_translate("MainWindow", "Only .xlsx format is supported", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bar Chart", None))
        self.comboBox_bar.setItemText(0, _translate("MainWindow", "Simple Column", None))
        self.comboBox_bar.setItemText(1, _translate("MainWindow", "2 Column", None))
        self.comboBox_bar.setItemText(2, _translate("MainWindow", "Batch Process", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Features", None))
        self.checkBox_Btitle.setText(_translate("MainWindow", "Title:", None))
        self.checkBox_Bylabel.setText(_translate("MainWindow", "Y axis label:", None))
        self.checkBox_Bxlabel.setText(_translate("MainWindow", "X axis label:", None))
        self.checkBox_Blegend.setText(_translate("MainWindow", "Legend:", None))
        self.comboBox_Blegend.setItemText(0, _translate("MainWindow", "Left", None))
        self.comboBox_Blegend.setItemText(1, _translate("MainWindow", "Right", None))
        self.comboBox_Blegend.setItemText(2, _translate("MainWindow", "Bottom", None))
        self.label_9.setText(_translate("MainWindow", "Legend Position:", None))
        self.checkBox_Bpercentage.setText(_translate("MainWindow", "Percentage", None))
        self.pushButton_Bprocess.setText(_translate("MainWindow", "Create Bar Chart", None))
        self.checkBox_Psorted.setText(_translate("MainWindow", "Sorted", None))
        self.comboBox_Bbcolor.setItemText(0, _translate("MainWindow", "Dark Blue", None))
        self.comboBox_Bbcolor.setItemText(1, _translate("MainWindow", "Blue", None))
        self.comboBox_Bbcolor.setItemText(2, _translate("MainWindow", "Shutter Blue", None))
        self.comboBox_Bbcolor.setItemText(3, _translate("MainWindow", "Dark Green", None))
        self.comboBox_Bbcolor.setItemText(4, _translate("MainWindow", "Yellow", None))
        self.comboBox_Bbcolor.setItemText(5, _translate("MainWindow", "Dark Pink", None))
        self.label_13.setText(_translate("MainWindow", "Bar color:", None))
        self.comboBox_Bpcolor.setItemText(0, _translate("MainWindow", "Indian Red", None))
        self.comboBox_Bpcolor.setItemText(1, _translate("MainWindow", "Red", None))
        self.comboBox_Bpcolor.setItemText(2, _translate("MainWindow", "Orange", None))
        self.comboBox_Bpcolor.setItemText(3, _translate("MainWindow", "Purple", None))
        self.comboBox_Bpcolor.setItemText(4, _translate("MainWindow", "Light Green", None))
        self.comboBox_Bpcolor.setItemText(5, _translate("MainWindow", "Light Blue", None))
        self.label_14.setText(_translate("MainWindow", "Percentage color:", None))
        self.label_2.setText(_translate("MainWindow", "Column 1", None))
        self.label_3.setText(_translate("MainWindow", "Column 2", None))
        self.label_6.setText(_translate("MainWindow", "Field", None))
        self.label_8.setText(_translate("MainWindow", "Angle", None))
        self.spinBox_Bangle.setSuffix(_translate("MainWindow", "°", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Pie Chart", None))
        self.comboBox_pie.setItemText(0, _translate("MainWindow", "Simple Column", None))
        self.comboBox_pie.setItemText(1, _translate("MainWindow", "2 Column", None))
        self.comboBox_pie.setItemText(2, _translate("MainWindow", "Batch Process", None))
        self.label_4.setText(_translate("MainWindow", "Column 2", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Features", None))
        self.checkBox_Ptitle.setText(_translate("MainWindow", "Title:", None))
        self.checkBox_Pexploded.setText(_translate("MainWindow", "Exploded", None))
        self.label_10.setText(_translate("MainWindow", "Legend Position:", None))
        self.comboBox_Plegend.setItemText(0, _translate("MainWindow", "Bottom", None))
        self.comboBox_Plegend.setItemText(1, _translate("MainWindow", "Side", None))
        self.pushButton_Pprocess.setText(_translate("MainWindow", "Create Pie Chart", None))
        self.spinBox_Pcollapsed.setSuffix(_translate("MainWindow", "%", None))
        self.label_11.setText(_translate("MainWindow", "Collapse if less than", None))
        self.comboBox_Pcolor.setItemText(0, _translate("MainWindow", "Blue-Green", None))
        self.comboBox_Pcolor.setItemText(1, _translate("MainWindow", "Color Mix", None))
        self.comboBox_Pcolor.setItemText(2, _translate("MainWindow", "Dark", None))
        self.label_12.setText(_translate("MainWindow", "Color Pattern:", None))
        self.label_5.setText(_translate("MainWindow", "Column 1", None))
        self.label_7.setText(_translate("MainWindow", "Field", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Create Excel Files", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "?", None))
        self.actionOpen.setText(_translate("MainWindow", "Browse", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

